# kintone plugin license sample program
# Copyright (c) 2024 Cybozu
# 
# Licensed under the MIT License
# https://opensource.org/license/mit/

AWSTemplateFormatVersion: 2010-09-09
Parameters:
  projectName:
    Type: String
    Default: kintonePluginLicense
Resources:
  KintonePluginLicenseApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${projectName}Api"
      Policy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: execute-api:Invoke
            Resource: "*"
          - Effect: Deny
            Principal: "*"
            Action: execute-api:Invoke
            Resource: "*"
            Condition:
              NotIpAddress:
                aws:SourceIp: 103.79.14.0/24
  APIResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref KintonePluginLicenseApi
      ParentId: !GetAtt KintonePluginLicenseApi.RootResourceId
      PathPart: license
  ApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref KintonePluginLicenseApi
      HttpMethod: POST
      AuthorizationType: NONE
      ResourceId: !Ref APIResource
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${projectName}Func/invocations
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref KintonePluginLicenseApi
      StageName: prod
    DependsOn: ApiMethod
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub "${projectName}Func"
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${KintonePluginLicenseApi}/*/POST/license
